# Step 3: 12-D Integral Based on Momentum
### Start by importing packages for easy functions & declare constants.
<font color = 'red'><b><u>NumPy</u></b></font> is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays. It also contains functionality for generating an array of random numbers.

In [83]:
import numpy as np

m = 1
gamma = 0.1*m
k0 = 1

num_val = 999999

### A quick note on NumPy's random.uniform() function:
We can use NumPy's <font color = 'red'>random.<b>uniform</b>(low, high, size)</font> to populate an array of size <font color = 'red'>size</font> with random values from <font color = 'red'>low</font> to <font color = 'red'>high</font>. "Uniform" indicates that the probability of returning any one values is the same for all values in the distribution, <sup>1</sup>&frasl;<sub>b-a</sub>

You can see below that we can display up to 51 decimal places of "precision," but NumPy does not actually offer anywhere near this amount of precision. It is a relic of a workspace with limited bits.

In [81]:
print('5 random values from -1 to 1 in a list: ', np.random.uniform(-1,1,5))

print('A full random value: ', format(np.random.uniform(-1,1,5)[1], '.51g'))

5 random values from -1 to 1 in a list:  [-0.76177308 -0.80823165 -0.23017025 -0.92435261  0.00398951]
A full random value:  0.03947250752063613532527597271837294101715087890625


### Declaring the 12 independent variables
We have four outgoing fermions with three axes for momentum. For now, we assume the "<b>importance sampling</b>" can be done by simply choosing momentum to be 1 for these outgoing particles: This adds extra simplicity because every variable can independently chosen randomly along the interval -1 to 1.

In [84]:
def pop_ferm(num_val):
    return [np.random.uniform(-1,1,num_val), np.random.uniform(-1,1,num_val), np.random.uniform(-1,1,num_val)]

pop_ferm(num_val)

[array([ 0.8930473 , -0.21078197, -0.57475676, ..., -0.96534587,
         0.4346825 ,  0.07685817]),
 array([-0.55100944,  0.65389919, -0.40721107, ...,  0.49876431,
         0.34956958,  0.03452505]),
 array([-0.62882756,  0.79924555, -0.10286063, ...,  0.54441221,
        -0.89684022, -0.78554026])]

### Declaring the 6 momenta of Higgsons
The first step is to populate the list momenta of the A and B Higgson

In [92]:
def pop_higg(fermion1, fermion2):
    array1 = np.array([a + b for a, b in zip(fermion1[0], fermion2[0])])
    print('\tA particular Higgson is 33% ...')
    array2 = np.array([a + b for a, b in zip(fermion1[1], fermion2[1])])
    print('\tA particular Higgson is 66% ...')
    array3 = np.array([a + b for a, b in zip(fermion1[2], fermion2[2])])
    print('\tA particular Higgson is 100% ...')
    return [array1, array2, array3]

fermi = pop_ferm(num_val)
pop_higg(fermi, fermi)

	A particular Higgson is 33% ...
	A particular Higgson is 66% ...
	A particular Higgson is 100% ...


[array([-0.16555169,  0.20954353, -0.72309656, ..., -0.81267103,
         0.82194207, -1.61772158]),
 array([ 0.62385234, -0.44851206, -0.64603362, ..., -0.32426192,
         0.42248696, -0.41598312]),
 array([ 0.33244354,  0.50651877, -0.34491453, ..., -1.84509085,
        -0.25159696,  0.13976289])]

### Now we can define the actual calculation
We can pass 2D higgsonA and higgsonB arrays (2D because they have a random list for x, y, and z directions), and the various constants k0, m, and gamma.

In [99]:
def do_calc(higgsonA, higgsonB, k0, m, gamma):
    tracker=20
    
    squaresA = []
    squaresB = []
    for i in range(0, len(higgsonA[0])):
        squaresA.append(higgsonA[0][i]**2 + higgsonA[1][i]**2 + higgsonA[2][i]**2)
        squaresB.append(higgsonB[0][i]**2 + higgsonB[1][i]**2 + higgsonB[2][i]**2)
        
        if tracker <= 100*i/(len(higgsonA[0])-1):
            print('Squares calculated (' + str(tracker) + '%) ...' )
            tracker += 20
    
    tracker=10
    function = []
    for i in range(0, len(higgsonA[0])):
        value1 = (k0**2-squaresA[i]-m**2)**2 + (m*gamma)**2
        value2 = (k0**2-squaresB[i]-m**2)**2 + (m*gamma)**2
        function.append(1/value1 + 1/value2)
        
        if tracker <= 100*i/(len(higgsonA[0])-1):
            print('Function calculated (' + str(tracker) + '%) ...' )
            tracker += 10
        
    return np.sum(function)/num_val

# Now the actual calculation
### Also contained here are all manipulable constants. It will generate new arrays every time.

In [100]:
# All of the current manipulable constants
num_val = 999999
m = 1
gamma = 0.1*m
k0 = 1

# Randomize the fermions
fermion1 = pop_ferm(num_val)
print('Fermions populated (25%) ...')
fermion2 = pop_ferm(num_val)
print('Fermions populated (50%) ...')
fermion3 = pop_ferm(num_val)
print('Fermions populated (75%) ...')
fermion4 = pop_ferm(num_val)
print('Fermions populated (100%) ...')

# Populate the higgsons with the newly randomized fermions
higgsonA = pop_higg(fermion1, fermion2)
print('Higgsons populated (50%) ...')
higgsonB = pop_higg(fermion3, fermion4)
print('Higgsons populated (100%) ...')

# Do the calculation and print it
print('\nFinal answer: \n' + str(do_calc(higgsonA, higgsonB, k0, m, gamma)))

Fermions populated (25%) ...
Fermions populated (50%) ...
Fermions populated (75%) ...
Fermions populated (100%) ...
	A particular Higgson is 33% ...
	A particular Higgson is 66% ...
	A particular Higgson is 100% ...
Higgsons populated (50%) ...
	A particular Higgson is 33% ...
	A particular Higgson is 66% ...
	A particular Higgson is 100% ...
Higgsons populated (100%) ...
Squares calculated (20%) ...
Squares calculated (40%) ...
Squares calculated (60%) ...
Squares calculated (80%) ...
Squares calculated (100%) ...
Function calculated (10%) ...
Function calculated (20%) ...
Function calculated (30%) ...
Function calculated (40%) ...
Function calculated (50%) ...
Function calculated (60%) ...
Function calculated (70%) ...
Function calculated (80%) ...
Function calculated (90%) ...
Function calculated (100%) ...

Final answer: 
5.8990671546443725


# The cell below contains only the single-file executable sent out as a .py: It is unnecessary if you have access to this notebook.

In [101]:
import numpy as np

m = 1
gamma = 0.1*m
k0 = 1

num_val = 999999

def pop_ferm(num_val):
    return [np.random.uniform(-1,1,num_val), np.random.uniform(-1,1,num_val), np.random.uniform(-1,1,num_val)]

def pop_higg(fermion1, fermion2):
    array1 = np.array([a + b for a, b in zip(fermion1[0], fermion2[0])])
    print('\tA particular Higgson is 33% ...')
    array2 = np.array([a + b for a, b in zip(fermion1[1], fermion2[1])])
    print('\tA particular Higgson is 66% ...')
    array3 = np.array([a + b for a, b in zip(fermion1[2], fermion2[2])])
    print('\tA particular Higgson is 100% ...')
    return [array1, array2, array3]

def do_calc(higgsonA, higgsonB, k0, m, gamma):
    tracker=20
    
    squaresA = []
    squaresB = []
    for i in range(0, len(higgsonA[0])):
        squaresA.append(higgsonA[0][i]**2 + higgsonA[1][i]**2 + higgsonA[2][i]**2)
        squaresB.append(higgsonB[0][i]**2 + higgsonB[1][i]**2 + higgsonB[2][i]**2)
        
        if tracker <= 100*i/(len(higgsonA[0])-1):
            print('Squares calculated (' + str(tracker) + '%) ...' )
            tracker += 20
    
    tracker=10
    function = []
    for i in range(0, len(higgsonA[0])):
        value1 = (k0**2-squaresA[i]-m**2)**2 + (m*gamma)**2
        value2 = (k0**2-squaresB[i]-m**2)**2 + (m*gamma)**2
        function.append(1/value1 + 1/value2)
        
        if tracker <= 100*i/(len(higgsonA[0])-1):
            print('Function calculated (' + str(tracker) + '%) ...' )
            tracker += 10
        
    return np.sum(function)/num_val


# Randomize the fermions
fermion1 = pop_ferm(num_val)
print('Fermions populated (25%) ...')
fermion2 = pop_ferm(num_val)
print('Fermions populated (50%) ...')
fermion3 = pop_ferm(num_val)
print('Fermions populated (75%) ...')
fermion4 = pop_ferm(num_val)
print('Fermions populated (100%) ...')

# Populate the higgsons with the newly randomized fermions
higgsonA = pop_higg(fermion1, fermion2)
print('Higgsons populated (50%) ...')
higgsonB = pop_higg(fermion3, fermion4)
print('Higgsons populated (100%) ...')

# Do the calculation and print it
print('\nFinal answer: \n' + str(do_calc(higgsonA, higgsonB, k0, m, gamma)))

Fermions populated (25%) ...
Fermions populated (50%) ...
Fermions populated (75%) ...
Fermions populated (100%) ...
	A particular Higgson is 33% ...
	A particular Higgson is 66% ...
	A particular Higgson is 100% ...
Higgsons populated (50%) ...
	A particular Higgson is 33% ...
	A particular Higgson is 66% ...
	A particular Higgson is 100% ...
Higgsons populated (100%) ...
Squares calculated (20%) ...
Squares calculated (40%) ...
Squares calculated (60%) ...
Squares calculated (80%) ...
Squares calculated (100%) ...
Function calculated (10%) ...
Function calculated (20%) ...
Function calculated (30%) ...
Function calculated (40%) ...
Function calculated (50%) ...
Function calculated (60%) ...
Function calculated (70%) ...
Function calculated (80%) ...
Function calculated (90%) ...
Function calculated (100%) ...

Final answer: 
5.879537215989484
